name: syncToGitee
on:
  push:
    branches:
      - '*'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/shabbyaaa'
          dst: 'gitee/shabbyshen'
          dst_key: ${{ secrets.dxSecretRsa }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "F2E"
          force_update: true
          debug: true
